CREATE TABLE `athlete_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`firstName` text,
	`lastName` text,
	`email` varchar(320),
	`phone` varchar(32),
	`city` text,
	`state` varchar(8),
	`zipCode` varchar(16),
	`graduationYear` varchar(8),
	`gpa` varchar(8),
	`satScore` varchar(8),
	`actScore` varchar(8),
	`intendedMajor` text,
	`primarySport` text,
	`positions` text,
	`jerseyNumber` varchar(8),
	`height` varchar(16),
	`weight` varchar(16),
	`keyStats` text,
	`awards` text,
	`highlightFilmUrl` text,
	`secondaryVideoUrl` text,
	`profilePhoto` text,
	`actionPhoto` text,
	`twitterHandle` varchar(64),
	`instagramHandle` varchar(64),
	`clubTeam` text,
	`verticalJump` varchar(16),
	`approachJump` varchar(16),
	`ncsaUrl` text,
	`hudlUrl` text,
	`highSchool` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `athlete_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `athlete_profiles_userId_unique` UNIQUE(`userId`)
);
